@backend_url = {{$dotenv BACKEND_URL}}
@google_client_id = {{$dotenv GOOGLE_CLIENT_ID}}
@google_client_secret = {{$dotenv GOOGLE_CLIENT_SECRET}}
@google_redirect_url = {{$dotenv GOOGLE_REDIRECT_URL}}
@facebook_client_id = {{$dotenv FACEBOOK_CLIENT_ID}}
@facebook_redirect_url = {{$dotenv FACEBOOK_REDIRECT_URL}}
###
GET {{backend_url}}/user/1,2,3,4

###
GET http://localhost:8080/user/1

###
GET {{backend_url}}/user/1?getBy=id

###
GET {{backend_url}}/user/1,2?getBy=id

###
# get all users
GET {{backend_url}}/user/all

###
GET https://accounts.google.com/o/oauth2/v2/auth?response_type=code&client_id={{google_client_id}}&scope=profile&redirect_uri={{google_redirect_url}}


###
https://accounts.google.com/o/oauth2/v2/auth?response_type=code&client_id=470765243423-876cqfkt6rss43ja20apa0q4bhkkbbd4.apps.googleusercontent.com&scope=profile+email&redirect_uri=http://localhost:8080/test/callback&nonce=ivancheungisgood

###
POST {{backend_url}}/auth/loginGoogle
Content-Type: application/json

{
    "googleAuthCode":"4/zwG4bH68CwExtK5ov3DBtEI5VcGqBoUNUKzKBi4rB6M6sihNBDXoDL8CIYyJ7M9fZpCIpx2sPsQANZN9xO1bWBY"
}

#####   -- AuthRouter Test --
###
POST {{backend_url}}/auth/loginGuest

###
POST {{backend_url}}/auth/token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJndWVzdElkIjoxMSwiaWF0IjoxNTkwMTMzMjg1LCJleHAiOjE1OTI3MjUyODV9.OTMwDEE2_Fpss2_vaKbgGiBjfnkeJtBQVG3hljBIcY1tefOJs6NjKLvJk05cNUhEbKkqfVDJ9xSA10QHC3av9ybN320gb3-WtluYBj1zfrrY3qbJCNxLIDK0tsXxScdQQnhW_pVsZ5ct33L4RyTAcCqqdUQ6OawSwFHzABXq1zc"
}

###
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJndWVzdElkIjo5LCJpYXQiOjE1OTAxMzI2NjgsImV4cCI6MTU5MjcyNDY2OH0.OI7cuijZLSETr_C9fkHqgwUXc1C4mNrNNesSBWSfNs9c9y_gwkKjP0PJuy7DK0qZQK2kxShVIr0FsW7L02BAqenIU8Vw1Rz6QlInPmJeo2Mzal4FUQ_BKE2MIHr0K3SlH1gbe0FolThNh8m_VF18eFcqyEXN210tH0ECsbEJWto

###
DELETE  {{backend_url}}/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJndWVzdElkIjoxMywiaWF0IjoxNTkwMTMzMjkwLCJleHAiOjE1OTI3MjUyOTB9.d-LjSuB36U152lnbOy2QMqpXNYZ3nrdqcek52N6Z9jeKfc6eG9dtcXEU8VJqKSwpCUZzArT8B3fqbxnAyVySJh6L6Y5hTQcggw2CwC4q1p1Uza0SGLduV6k_0Nhng3jJCrFVp_K-IvE5a7Cca8nqY0PvNAFbOGz2ejnhb69BOKY"
}

### Facebook
https://www.facebook.com/v7.0/dialog/oauth?client_id={{facebook_client_id}}&redirect_uri=http://localhost:8080/callback&state=stststst

###
https://www.facebook.com/v7.0/dialog/oauth?client_id=2313103855661187&redirect_uri=http://localhost:8080/test/callback&state=stststst&response_type=token&scope=user_videos

curl -i -X GET "https://graph.facebook.com/611099456422217/comments?access_token=EAAg3wXWlMIMBAMTb8eJuBLxmlVbkZAV3SWEc8qXGOw2plZANFqwXIkeSzQK12XZBlYyiFaZCikXXecvdARXPveh0R2Iqs0KbTL5b0YZCZBOPOdGWiCGPEz1hLke7AZALqtH3dqCrqX4pcatWCW8bZBzAu4ZAtMaOf2nLHIHhGZAXY1OAz9p6KO9AZB0QPt4XYEjXZAQZD"